NinetyNineCatsAuth/config/routes.rb
Rails.application.routes.draw do
  resources :cats
  resources :cat_rental_requests, only: [:new, :create, :destroy]
  resource :user, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]

  post '/cat_rental_requests/approve' => 'cat_rental_requests#approve'
  post '/cat_rental_requests/deny' => 'cat_rental_requests#deny'
end

NinetyNineCatsAuth/app/models/cat_rental_request.rb
class CatRentalRequest < ActiveRecord::Base
  STATUSES = ["PENDING", "APPROVED", "DENIED"]

  validates :cat_id, :start_date, :end_date, :status, :user_id,
            presence: true
  validates :status, inclusion:
            { in: STATUSES,
              message: "Illegal status"}
  validate :no_overlapping_approved
  validate :cat_exists

  belongs_to(
    :requestor,
    :foreign_key => :user_id,
    :primary_key => :id,
    :class_name => 'User'
  )

  belongs_to :cat
  after_initialize :set_status

  def set_status
    self.status ||= "PENDING"
  end

  def approve!
    self.status = "APPROVED"

    changed_requests = overlapping_pending_requests.each do |req|
      req.status = "DENIED"
    end

    changed_requests << self

    Cat.transaction do
      changed_requests.map { |request| request.save! }
    end
  end

  def deny!
    self.status = "DENIED"
    self.save
  end

  def pending?
    self.status == "PENDING"
  end

  def overlapping_requests
    overlapping = <<-SQL, {start_date: start_date, end_date: end_date, id: id, cat_id: cat_id}
        NOT ((cat_rental_requests.start_date > :end_date)
      OR
        (cat_rental_requests.end_date < :start_date))
      AND
        cat_rental_requests.id != :id
      AND
        cat_rental_requests.cat_id = :cat_id
    SQL

    CatRentalRequest.where(overlapping)
  end

  def overlapping_approved_requests
    approved = <<-SQL
      cat_rental_requests.status = 'APPROVED'
    SQL

    overlapping_requests.where(approved)
  end

  def overlapping_pending_requests
    pending = <<-SQL
      cat_rental_requests.status = 'PENDING'
    SQL

    overlapping_requests.where(pending)
  end

  private
    def no_overlapping_approved
      return unless status == "APPROVED"
      unless overlapping_approved_requests.empty?
        errors[:base] << "Cannot overlap with an approved request"
      end
    end

    def cat_exists
      errors[:base] << "Cat doesn't exist" unless Cat.exists?(cat_id)
    end

end

NinetyNineCatsAuth/app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController
  before_action :require_cat_ownership, only: [:approve, :deny]
  before_action :require_user!, only: [:new, :create]

  def approve
    @request = CatRentalRequest.find(params[:cat_rental_request][:id])
    begin
      @request.approve!
    rescue ActiveRecord::RecordInvalid
    end
    redirect_to cat_url(params[:cat][:id])
  end

  def create
    @request = current_user.requests.new(request_params)
    @cat = Cat.find(request_params[:cat_id])
    @cats = Cat.all

    if @request.save
      redirect_to cat_url(@cat)
    else
      render :new
    end
  end

  def deny
    @request = CatRentalRequest.find(params[:cat_rental_request][:id])
    begin
      @request.deny!
    rescue ActiveRecord::RecordInvalid
    end
    redirect_to cat_url(params[:cat][:id])
  end

  def new
    @request = CatRentalRequest.new
    @cats = Cat.all
    render :new
  end

  private
    def request_params
      params.require("cat_rental_request").permit("cat_id", "start_date", "end_date")
    end

    def current_cat
      Cat.find(params[:cat][:id])
    end
end

NinetyNineCatsAuth/app/helpers/cat_rental_requests_helper.rb
module CatRentalRequestsHelper
end

NinetyNineCatsAuth/app/views/cat_rental_requests/index.html.erb
<h1> <%= @cat.name %>'s Rental Requests </h1>

<table>
  <tr>
    <td> Start Date:</td>
    <td> End Date:  </td>
  </tr>

  <% @cat.cat_rental_requests.each do |request| %>
  <tr>
      <td> <%= request.start_date %> </td>
      <td> <%= request.end_date %> </td>
  </tr>
    <% end %>

</table>

NinetyNineCatsAuth/app/views/cat_rental_requests/new.html.erb
<h1> Request a Cat Rental</h1>

<%= @request.errors.full_messages %>

<form action="<%= cat_rental_requests_url %>" method="post">
  <input  type="hidden"
         name="authenticity_token"
         value="<%= form_authenticity_token %>">

  <label for="request_cat_name">Pick a cat: </label>
  <select id="request_cat_name" name="cat_rental_request[cat_id]">
    <% @cats.each do |cat| %>
      <option value="<%= cat.id %>" <%= "selected" if @request.cat_id == cat.id %>
        ><%= cat.name.capitalize %></option>
    <% end %>
  </select>
  <br>

  <label for="request_start_date">Start date:</label>
  <input  id="request_start_date"
          type="date"
          name="cat_rental_request[start_date]"
          value="<%= @request.start_date %>">
  <br>
  <label for="request_end_date">End date:</label>
  <input  id="request_end_date"
          type="date"
          name="cat_rental_request[end_date]"
          value="<%= @request.end_date %>">

  <input type="submit" value="Request cat">

</form>