MusicApp/config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]

  resources :bands do
    resources :albums, only: :new
  end

  resources :albums, except: [:new, :index] do
    resources :tracks, only: :new
  end

  resources :tracks, except: [:new, :index] do
    resources :notes, only: :create
  end

  resources :notes, only: :destroy
end

MusicApp/app/models/track.rb
class Track < ActiveRecord::Base
  validates :name, :album_id, presence: true

  belongs_to :album
  has_one :band, through: :album, source: :band
  has_many :notes


  enum track_type: [:regular, :bonus]
  after_initialize :ensure_track_type


  def album_name
    album.name
  end

  def band_name
    album.band_name
  end

  private
    def ensure_track_type
      self.track_type ||= 0
    end
end

MusicApp/app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_action :require_user

  def show
    @track = Track.find(params[:id])
    render :show
  end

  def new
    @track = Track.new
    @album = Album.find(params[:album_id])
    @albums = Album.all

    render :new
  end

  def create
    @track = Track.new(track_params)

    if @track.save
      redirect_to album_url(@track.album_id)
    else
      @album = Album.find(@track.album_id)
      @albums = Album.all
      render :new
    end
  end

  def edit
    @track = Track.find(params[:id])
    @track_name = @track.name
    @albums = Album.all
    @album = @track.album
    render :edit
  end

  def update
    @track = Track.find(params[:id])
    @track_name = @track.name

    if @track.update(track_params)
      redirect_to track_url(@track)
    else
      @albums = Album.all
      @album = @track.album
      render :edit
    end
  end

  def destroy
    @track = Track.find(params[:id])
    @track.destroy!
    redirect_to album_url(@track.album_id)
  end

  private
    def track_params
      params.require(:track).permit(:lyrics, :name, :album_id, :track_type)
    end
end

MusicApp/app/helpers/tracks_helper.rb
module TracksHelper
end

MusicApp/app/views/tracks/edit.html.erb
<h1>Edit "<%= @track_name %>"!</h1>

<%= render partial: "shared/errors", locals: {obj: @track} %>

<form action="<%= track_url(@track) %>" method="post">
  <%= auth_token %>
  <input type="hidden" name="_method" value="PATCH">

  <label for="track_name"><strong>Track name:</strong></label>
  <input id="track_name" type="text" name="track[name]" value="<%= @track.name %>">
  <br>

  <label for="track_album"><strong>Album:</strong></label>
  <select id="track_album" name="track[album_id]">
    <%= listed_options(@albums, @album) %>
  </select>
  <br>

  <strong>Track Type:</strong>
  <br>
  <label for="Regular">Regular</label>
  <input  id="Regular"
          type="radio"
          name="track[track_type]"
          value="regular"
          <%= "checked" if @track.track_type == "regular" %> >

  <label for="bonus">Bonus</label>
  <input  id="bonus"
          type="radio"
          name="track[track_type]"
          value="bonus"
          <%= "checked" if @track.track_type == "bonus" %> >
  <br>

  <label for="track_lyrics"><strong>Lyrics:</strong></label>
  <br>
  <textarea  id="track_lyrics"
          name="track[lyrics]"><%= @track.lyrics %></textarea>

  <button>Submit!</button>
</form>

MusicApp/app/views/tracks/new.html.erb
<h1>Add a new track to "<%= @album.name %>"!</h1>

<%= render partial: "shared/errors", locals: {obj: @track} %>

<form action="<%= tracks_url %>" method="post">
  <%= auth_token %>

  <label for="track_name"><strong>Track name:</strong></label>
  <input id="track_name" type="text" name="track[name]" value="<%= @track.name %>">
  <br>

  <label for="track_album"><strong>Album:</strong></label>
  <select id="track_album" name="track[album_id]">
    <%= listed_options(@albums, @album) %>
  </select>
  <br>

  <strong>Track Type:</strong>
  <br>
  <label for="Regular">Regular</label>
  <input  id="Regular"
          type="radio"
          name="track[track_type]"
          value="regular"
          <%= "checked" if @track.track_type == "regular" %> >

  <label for="bonus">Bonus</label>
  <input  id="bonus"
          type="radio"
          name="track[track_type]"
          value="bonus"
          <%= "checked" if @track.track_type == "bonus" %> >
  <br>

  <label for="track_lyrics"><strong>Lyrics:</strong></label>
  <br>
  <textarea  id="track_lyrics"
          name="track[lyrics]"><%= @track.lyrics %></textarea>

  <button>Submit!</button>
</form>

MusicApp/app/views/tracks/show.html.erb
<h1> <%= @track.name %> </h1>

<strong>Band:</strong> <%= @track.band_name %>
<br>

<strong>Album:</strong> <%= @track.album_name %>
<br>

<strong>Track type:</strong>
<%= @track.track_type.capitalize %>

<br>
<strong>Lyrics:</strong>
<br>
<pre>
<%= ugly_lyrics(@track.lyrics) %>
</pre>

<br>
<br>

<a href="<%= edit_track_url %>">Edit track</a>
<br>

<form action="<%= track_url(@track) %>" method="post">
  <%= auth_token %>
  <input type="hidden" name="_method" value="DELETE">
  <button>Delete track</button>
</form>
<%= render partial: "notes/note", locals: {track: @track} %>
<%= render partial: "notes/form", locals: {track: @track} %>

<br>
<br>

<a href="<%= album_url(@track.album) %>" >Back to album</a>